engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript:
          mass_threshold: 58
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**/*"
exclude_paths:
- test/
- coverage/
- example/
