/**
* Message translations.
*
* This file is automatically generated by the 'yarn run translations extract'
* command. It contains the localizable messages extracted from source code.
*
* You may modify this file by translating the extracted messages.
*
* Each object element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
*
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check the documentation
* for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
module.exports = {
  "Extract me": "Extrais moi",
  "I'm using a named {placeholder}": "",
  "I'm using two numerical {0} {1}": "",
  "I'm using a {0} numerical placeholder": "",
  "hello {user}": "bonjour {user}",
  "You don't know me": "",
  "I'm known, but untranslated": "",
  "simple sentence": "",
  "{placeholder} at start": "",
  "Placeholder {at} middle": "",
  "Placeholder in the {end}": "",
  "This uses a {💩} as a placeholder": "",
  "Two {consecutive} {placeholders}!": "",
  "Same {placeholder} {placeholder}": "",
  "This {0} is {1}": "",
  "This {1} is {0}": "",
  "This will {0} well!": "",
  "Warn about {missing} placeholder": "",
  "unused": "@obsolete@"
};