/**
 * Message translations.
 *
 * This file is automatically generated by the 'yarn run translations extract'
 * command. It contains the localizable messages extracted from source code.
 *
 * You may modify this file by translating the extracted messages.
 *
 * Each object element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check the documentation
 * for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
module.exports = {
  "I think that {user} made {repository} public": "Creo que {user} hizo {repository} público",
  "This string is not translated and will automatically fallback to {language}": "",
  "This string should not trigger placeholders processing": "",
  "This string uses {nested}": "",
  "nested translating!": "",
  "Oops, I forgot to pass my {placeholder}": "",
  "A simple sentence without placeholders": "",
  "Two {consecutive} {placeholders}": "",
  "consecutive": "",
  "placeholders": "",
  "A sentence {0} using {1} numerical {0} placeholders": "",
  "A simple sentence with only one placeholder passed as a {0} without wrapping it in an array": "",
  "There {n,plural,=0{are no cats} =1{is one cat} =*{are # cats}}!": "",
  "Hello {name}. This is a component using t()": ""
};